import type { Metadata } from "next";

/**
 * Link-preview metadata for /claim/[id] (audit 4D / B2).
 *
 * The claim page is a client component, so it cannot export its own metadata.
 * This sibling layout is a server component that provides it. We do NOT fetch
 * the on-chain amount here (that would add latency to every page load and the
 * amount is already shown on the page itself); instead the preview is static
 * and honest.
 *
 * og:image points at a static, brand-matched thumbnail (public/og-claim.png,
 * generated by scripts/make-og-image.mjs) so WhatsApp/SMS/X show a card, not a
 * bare URL. The absolute URL is built from the host on request, so it stays
 * correct on remitlink.vercel.app and on any dev tunnel alike.
 */
export async function generateMetadata({
  request,
}: {
  request: Request;
}): Promise<Metadata> {
  const host = request.headers.get("host") ?? "remitlink.vercel.app";
  const image = `https://${host}/og-claim.png`;

  return {
    title: "You received money - RemitLink",
    description:
      "Someone sent you money. Open this link and claim it with your passkey - no account or forms needed.",
    openGraph: {
      title: "You received money",
      description:
        "Claim your money with your passkey - no account, no forms.",
      type: "website",
      siteName: "RemitLink",
      images: [{ url: image, width: 1200, height: 630 }],
    },
    twitter: {
      card: "summary_large_image",
      title: "You received money - RemitLink",
      description: "Claim your money with your passkey - no account, no forms.",
      images: [image],
    },
  };
}

export default function ClaimLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
