import type { Metadata } from "next";

/**
 * Link-preview metadata for /claim/[id] (audit 4D / B2).
 *
 * The claim page is a client component, so it cannot export its own metadata.
 * This sibling layout is a server component that provides it. We do NOT fetch
 * the on-chain amount here (that would add latency to every page load and the
 * amount is already shown on the page itself); instead the preview is static
 * and honest.
 *
 * og:image points at a static, brand-matched thumbnail (public/og-claim.png,
 * generated by scripts/make-og-image.mjs).
 *
 * Base URL: NEXT_PUBLIC_APP_URL if set (dev tunnels), else the production
 * domain - which is passkey-bound and will never change (AGENT.md §4/§8),
 * so hardcoding the fallback is safe.
 *
 * BUGFIX 2026-10-06: an earlier version read the host from `request` in the
 * generateMetadata context - but Next.js does NOT pass `request` there
 * (context is { params, searchParams }), so `request` was undefined and the
 * whole /claim/[id] route 500'd on the server ("Cannot read properties of
 * undefined (reading 'headers')", Vercel digest 2765141040). Do not put the
 * Request object back in here.
 */
export function generateMetadata(): Metadata {
  const base =
    process.env.NEXT_PUBLIC_APP_URL ?? "https://remitlink.vercel.app";
  const image = `${base}/og-claim.png`;

  return {
    title: "You received money - RemitLink",
    description:
      "Someone sent you money. Open this link and claim it with your passkey - no account or forms needed.",
    openGraph: {
      title: "You received money",
      description:
        "Claim your money with your passkey - no account, no forms.",
      type: "website",
      siteName: "RemitLink",
      images: [{ url: image, width: 1200, height: 630 }],
    },
    twitter: {
      card: "summary_large_image",
      title: "You received money - RemitLink",
      description: "Claim your money with your passkey - no account, no forms.",
      images: [image],
    },
  };
}

export default function ClaimLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
